### ISSUE TITLE
Make Unix style command line arguments

### ISSUE THREAD

**Issue by LuPro** [LuPro/SlabelFish#1]
(just) input prompts suck, allow all data to be specified when running (needed for proper use in other projects as well).

Command line arguments like
- v: verbose
- e: encode
- d: decode
- i: whether last argument is a file name or raw slab data

+ allow slab data to be passed via command line arg (evaluate: how long can those get? slabs can be 30kB max, maybe it needs to be entered some other way (via file or cross process pipe or the like)

**Comment by flofriday** [comment]
You are right, unix style arguments are awsome.
Even more amazing, there is the great [`argparse`](https://docs.python.org/3/library/argparse.html) pacakge from the python standard library.

I can only recommend that, the documentation is great and it automatically generates a `usage` message for you.

If you want to I can do this in an PR 😉

**Comment by LuPro** [comment]
currently working on it, note to myself: in future figure out whether the program is run by a user in a terminal or by another program to decide whether or not to drop into interactive mode in case of missing flags
