### ISSUE TITLE
Pythonic Python

### ISSUE THREAD

**Issue by flofriday** [LuPro/SlabelFish#5]
I am a real documentation & formatting nerd, so feel free to ignore some or all of this.

# Pythonic?
is used to refer to code that the python community sees as "beautiful" code. If you want to see some short list on what they mean as beautiful, you can read [PEP 20 -- The Zen of Python](https://www.python.org/dev/peps/pep-0020/).

The big advantage of having a pythonic code base is that other developers feel right at home in your code.

# Black
First of, I would advise anyone in any language to use an automatic codeformatter. Luckily for python there are many good ones, but I would recommend [black](https://github.com/psf/black). It is used by Dropbox, Mozilla, Quora and many more.

You can setup your editor to automatically run black on every save, which makes the formatting process seamless.

# Code Style
While black already helps a lot, it does not rewrite code (renaming variables etc)

Again python has an official style guide defined in [PEP 8 -- Style Guide for Python Code](https://www.python.org/dev/peps/pep-0008/), this is quite long and worth a read, but for now I will just mention the "violations" I found.

## Variable naming or "Python hates mixedCase"
As much as Java loves it Python hates it. Don't write your code likeJava write it like_python_in_snake_case.

Continuing on the topic of naming:
* variables, functions, methods: snake_case
* Classes, Exceptions: CamelCase
* Constants: UPPER_CASE

Naming Conventions in [PEP 8](https://www.python.org/dev/peps/pep-0008/#naming-conventions)

## For loops or "Don't write C-style-for-loops  in Python"
You have on two points loops like:
```python
total = 0
for i in range(len(byteList)):
    total = (total << 8) + byteList[i] 
```

Which could be way simpler with:
```python
total = 0
for byte in byteList:
    total = (total << 8) + byte 
```

Sometimes you need to have an counter to know on which iteration you are, 
in that case it is convention to use `enumerate`.
```python
total = 0
for i, byte in enumerate(byteList):
    total = (total << 8) + byte 
    print(i) #Or something else
```

## Context managers or "you forgot to call `.close()`"
So you opened `slabFile` but never closed it (which is honestly not a problem at all, since this script only runs for a short time and then terminates, at which point the OS closes everything for you anyway). 

However, it is still best practise to close files after usage. You can close like in C with an explicit call:
```python
#read slab
slabFile = open(slabFileName, "r")
slabRawData = slabFile.read()
slabFile.close()
```

However, remembering to put one (and only one) `.close()` call for every file is hard, which is why golang has the [`defer`](https://tour.golang.org/flowcontrol/12) keyword. I know this is python but who would I be if I wouldn't sneak in a little bit of go in every conversation 😉.

So python also has a solution called [Context managers](https://book.pythontips.com/en/latest/context_managers.html).
Whit a context manager the code looks like this:

```python
#read slab
with open(slabFileName, "r") as slabFile:
    # File is open here 
    slabRawData = slabFile.read()

# File is closed when you leave the indentation block
```

# Conclusion
> Now is better than never

What I want to say, is that this an amazing usage of python and who really cares if it is beautiful formatted when it is a useful tool? 

Great work 👍🎉

**Comment by LuPro** [comment]
Need to refactor anyways, good point to actually read up on pythonic ways of coding
