### ISSUE TITLE
It's not JSON output

### ISSUE THREAD

**Issue by flofriday** [LuPro/SlabelFish#6]
The output is definitely human-readable, and while it looks _like_ JSON it is  unfortunately not valid JSON.

For example python uses single quotes when printing strings and JSON requires double qoutes.

## Example
```
>>> import json
>>> me = {"name": "flofriday", "age": 42}
>>> print(me)
{'name': 'flofriday', 'age': 42}
>>> print(json.dumps(me))
{"name": "flofriday", "age": 42}
```

## Fix
Use `print(json.dumps(assets))`

**Comment by LuPro** [comment]
yeah, I think I added that as a comment at some point in the code, definitely need to do actual JSON output :P

**Comment by flofriday** [comment]
Also you can make it more human readable by letting python "format" the json with the `indent` argument:

```python
>>> import json
>>> me = {"name": "flofriday", "age": 42}
>>> print(json.dumps(me, indent=2))
{
  "name": "flofriday",
  "age": 42
}
```

**Comment by LuPro** [comment]
that's some good stuff, thanks python for doing everything I ever want it to

**Comment by flofriday** [comment]
Well python cannot color the json output (per default). But for fancy stuff like that there is always [jq](https://stedolan.github.io/jq/) the swiss army knife for JSON on the console.
